### ISSUE TITLE
Null error on inventory click event

### ISSUE THREAD

**Issue by wingzero54** [CivMC/ExilePearl#26]
[11:19:29] [Server thread/ERROR]: Could not pass event InventoryClickEvent to ExilePearl v2.0.0-SNAPSHOT
java.lang.ArrayIndexOutOfBoundsException: null

No stack trace or other information, but this error comes up quite a bit. Probably easy to replicate by moving a pearl around in your inventory I assume

**Comment by Diet-Cola** [comment]
Can you possibly grab original stack trace due to 10k + occurrences pls

**Comment by Diet-Cola** [comment]
Bump

**Comment by wingzero54** [comment]
Yup I always forget it cuts off the stack trace. 

[08:18:24] [Server thread/ERROR]: Could not pass event InventoryClickEvent to ExilePearl v2.0.0-SNAPSHOT
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 36
	at java.util.Arrays$ArrayList.get(Unknown Source) ~[?:?]
	at net.minecraft.core.NonNullList.get(NonNullList.java:44) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.world.entity.player.Inventory.getItem(Inventory.java:616) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftInventory.getItem(CraftInventory.java:49) ~[paper-1.18.2.jar:git-Paper-387]
	at com.devotedmc.ExilePearl.listener.PlayerListener.onInventoryClick(PlayerListener.java:575) ~[ExilePearl-paper-2.0.0-SNAPSHOT.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor570.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-387]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2861) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1400) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1377) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1370) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1348) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[paper-1.18.2.jar:git-Paper-387]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
	at java.lang.Thread.run(Unknown Source) ~[?:?]

**Comment by Diet-Cola** [comment]
Ok so now we need reproducable info on this

```
else if(event.getAction() == InventoryAction.HOTBAR_SWAP) {
			PlayerInventory playerInventory = event.getWhoClicked().getInventory();
			ExilePearl pearl = pearlApi.getPearlFromItemStack(playerInventory.getItem(event.getHotbarButton()));
```

`event.getHotbarButton()` is returning -1 because it is not a number key action
